### ISSUE TITLE
rewrite londonlaw in python3?

### ISSUE THREAD

**Issue by horald** [anyc/londonlaw#1]
Are there efforts to rewrite londonlaw in python3? Or are there programmers who could help me do this?

**Comment by gkuznik** [comment]
Seems like this project is pretty dead. The last commit was made in 2015. I would like to help you though.

**Comment by horald** [comment]
Yes, that would be nice. I have created a Folk under https://github.com/horald/londonlaw . Shall I create a branch and unlock it for you?

**Comment by gkuznik** [comment]
Yeah, that would be nice.

**Comment by anyc** [comment]
Thank you for working on this! Unfortunately, I do not have time for this project anymore. If you plan to keep working on this, I would gladly refer visitors to your repository.

**Comment by horald** [comment]
Thanks for the feedback. The fork ([https://github.com/horald/londonlaw](https://github.com/horald/londonlaw)) for python3 from londonlaw is ready! So feel free to point visitors to my repository.

**Comment by anyc** [comment]
Sorry for the delay! I updated the Readme. By the way, it would help if you could invest a few seconds in proper commit messages. ;)
